CREATE TABLE IF NOT EXISTS sources (
  source_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT,
  status TEXT,
  mode TEXT,
  category TEXT,
  items INTEGER DEFAULT 0,
  latency_ms INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS items (
  id TEXT PRIMARY KEY,
  source_id TEXT REFERENCES sources(source_id),
  source_name TEXT,
  category TEXT,
  authority TEXT,
  title TEXT NOT NULL,
  url TEXT,
  published_at DATE,
  tags_json JSONB DEFAULT '[]'::jsonb,
  scene TEXT,
  consulting_value TEXT,
  public_value TEXT,
  ingestion TEXT,
  score INTEGER DEFAULT 0,
  content_hash TEXT,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS source_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_type TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  item_count INTEGER DEFAULT 0,
  source_count INTEGER DEFAULT 0,
  added_count INTEGER DEFAULT 0,
  message TEXT
);

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'public',
  industry TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS watchlists (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  categories_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS saved_items (
  user_id TEXT NOT NULL,
  item_id TEXT NOT NULL REFERENCES items(id),
  saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, item_id)
);

CREATE TABLE IF NOT EXISTS briefs (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  brief_type TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  summary TEXT NOT NULL,
  items_json JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_items_category_date ON items(category, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_items_source_date ON items(source_id, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_runs_started ON source_runs(started_at DESC);

